import Head from "next/head";
import {
  AiOutlineInstagram,
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/lahu.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web7 from "../public/web7.png";
import web8 from "../public/web8.png";
import web9 from "../public/web9.png";
import web10 from "../public/web10.png";
import web11 from "../public/web11.png";
import web12 from "../public/web12.png";
import web13 from "../public/web13.png";
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"></link>

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Lahu's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/lahu.png" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Lahu Andhale</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1bB7usS5QpoVSYhk73sJqtUn4ZVKhib7c/view?usp=drivesdk"
                >
                  Resume 
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Lahu Andhale
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and Engineer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. 
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.instagram.com/lahuandhale123/">   
            <AiOutlineInstagram/>
            </a>
              <a href="https://www.linkedin.com/in/lahu-andhale-677509240/">
              <AiFillLinkedin />
              </a>
              <a href="https://github.com/Lahu19">
              <AiFillGithub/>
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote Internship form
              <span className="text-teal-500"> DEVTOWN.LTD </span>
              Focus on <span className="text-teal-500">Startups </span>
              and always try to collaborate with talanted people to create digital products
              for both business and customer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including design, develop and
              programming.
            </p>
          </div>
          <div className="lg:flex gap-15 ">

          <div className="text-center shadow-lg p-10 rounded-xl my-10 py-10 px-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className=" pt-8 pb-2 font-bold text-xl ">
                Projects
              </h3>
              <p className="py-2 px-4">
                I have done the projects fully functional and Responsible projects.
              </p>
              <h4 className="py-4 px-4 text-teal-600">Technologies I Use</h4>
              <p className="text-gray-800 py-1">MERN Technologies</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">API's</p>
              <p className="text-gray-800 py-1">ChatGPT</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl m-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className=" pt-8 pb-2 font-bold text-xl ">
                Eduction
              </h3>
              <p className="py-2">
                I have done My Eduction.
              </p>
              <h4 className="py-4 text-teal-600">Graduation</h4>
              <p className="text-gray-800 py-1">D.Y.Patil.College</p>
              <h4 className="py-4 text-teal-600">HSC</h4>
              <p className="text-gray-800 py-1">R.C.Shahu College</p>
              <h4 className="py-4 text-teal-600">SSC</h4>
              <p className="text-gray-800 py-1">Dr.K.M.M.Doshi Highschool</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className=" pt-8 pb-2 font-bold text-xl ">
                Languages
              </h3>
              <p className="py-2">
                Languages Known...
              </p>
              <h4 className="py-4 text-teal-600"> Coding Languages that i learned</h4>
              <p className="text-gray-800 py-1">C C++</p>
              <p className="text-gray-800 py-1">JAVA</p>
              <h4 className="py-4 text-teal-600">Languages that I learned</h4>
              <p className="text-gray-800 py-1">English</p>
              <p className="text-gray-800 py-1">Marathi</p>
              <p className="text-gray-800 py-1">Hindi</p>
            </div>
            
          </div>
        </section>
        <section className="py-10">
        <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a full stack web developer, I've done remote Internship form
              <span className="text-teal-500"> DEVTOWN.LTD </span>
              Focus on <span className="text-teal-500">Startups </span>
              and always try to collaborate with talanted people to create digital products
              for both business and customer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including design, develop and
              programming.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web7}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web8}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web9}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web10}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web11}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web12}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web13}
              />
            </div>
          </div>
        </section>
      </main>

      <div> 
        <div className="my=10%">Contact if any quary</div>
      </div>
    </div>
    
  );
}
